events {
    worker_connections 1024;
}

# Bắt buộc phải dùng khối 'stream' cho kết nối TCP (Socket), không dùng 'http'
stream {
    upstream gartic_backend {
        # host.docker.internal giúp Nginx trong Docker trỏ ngược ra máy tính Windows của bạn
        server host.docker.internal:8001; 
        server host.docker.internal:8002;
    }

    server {
        listen 8080; # Cổng mà WinForms sẽ gọi vào
        proxy_pass gartic_backend;
        
        # Giữ kết nối không bị ngắt tự động
        proxy_timeout 1h;
        proxy_connect_timeout 5s;
    }
}